version: "3.7"
services:
    www:
        build: .  
        ports: 
            - "8000:80"
        links:
            - db
    db:
        image: mysql:5.7
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: kuiz
            MYSQL_USER: user
            MYSQL_PASSWORD: Test@123
            MYSQL_ROOT_PASSWORD: 12345
